Added docker workflow for api
Alv-no/alvtime pull request #211
Opened 2020-12-02 15:15 UTC by palbock90

2020-12-02 15:27 UTC, TheKnarf requested changes
I suggest that we split up the github workflow per package instead of adding a lot of stuff to the same pipeline. I don't think there's any practical limit on how many pipelines we can have.

@Trulsaa may have some opinion if we should continue to build and push docker images from the github workflow or if it should be moved over to Azure.

Maybe we three should have a meeting to discuss this?

2020-12-02 15:27 UTC, TheKnarf commented on .github/workflows/docker-push-dev.yml
> +  IMAGE_NAME_API: alvnoas/alvtime-web-api-dev
Maybe we should split this up into one pipeline per package?

2020-12-02 15:27 UTC, TheKnarf commented on Readme.md
> +| [Api](./packages/api)               | Backend   | Backend api                  |
Was there any point in reformating this? I think formating it like you have done will make it harder to maintain in the future.

2020-12-02 15:32 UTC, palbock90 commented
> 
> 
> I suggest that we split up the github workflow per package instead of adding a lot of stuff to the same pipeline. I don't think there's any practical limit on how many pipelines we can have.
> 
> @Trulsaa may have some opinion if we should continue to build and push docker images from the github workflow or if it should be moved over to Azure.
> 
> Maybe we three should have a meeting to discuss this?

Vi kan godt ha et møte. Per nå bygges docker images for backend i Azure og jeg ser noen fordeler med å flytte det over til github workflows.

2020-12-02 15:32 UTC, palbock90 commented on Readme.md
> +| [Api](./packages/api)               | Backend   | Backend api                  |
Det var ikke meningen å reformatere :S Det må VS code ha gjort av seg selv. Jeg rettet bare opp et par skriveleifer.

2020-12-02 15:50 UTC, Trulsaa commented
Tar gjerne en prat om dette. Digger at du kjører på med workflows @palbock90. Jeg har også sett litt på muligheten for å dytte docker imaget direkte til app servicen. Men da bør vi nok gjøre det i devOps. Spent på hva dere tenker.

2020-12-03 17:13 UTC, TheKnarf approved these changes

2020-12-03 17:14 UTC, merged