Fixes overtime. #195, #194
Alv-no/alvtime pull request #221
Opened 2020-12-03 23:03 UTC by klyngen

Added overtime hours and fixes for overtime-ui #214

Solves issues #194, #195, #214

2020-12-04 08:48 UTC, Trulsaa requested changes
Utrolig mye bra her. Det ser virkelig ut som at vi nærmer oss noe i forhold til overtid og avspasering. Jeg tar gjerne en parrprogramering session for å se over de tingene jeg har kommentert.

2020-12-04 08:48 UTC, Trulsaa commented on packages/frontend/src/store/timeEntries.ts
> +          dispatch("FETCH_AVAILABLE_HOURS");
Klarer vi å legge denne et mere logisk sted? DDEBOUNCED_PUSH_TIME_ENTRIES bør ikke bli en samle plass for å oppdatere data. Jeg blir gjerne med på å tenke ut en bedre måte.

2020-12-04 08:48 UTC, Trulsaa commented on packages/frontend/src/store/timeEntries.ts
> +      dispatch("FETCH_AVAILABLE_HOURS");
Ref kommentaren på ny dispatch i DEBOUNCED_PUSH_TIME_ENTRIES. Finnes det ikke noen computed greier i Vue der man kan kjøre denne dispatchen vær gang en commit av UPDATE_TIME_ENTRIES har blitt kjørt

2020-12-04 08:48 UTC, Trulsaa commented on packages/frontend/src/components/HoursWithdrawal.vue
> +  watch: {},
Fjerne?

2020-12-04 08:48 UTC, Trulsaa commented on packages/frontend/src/components/HoursWithdrawal.vue
>            :disabled="!isNumber"
Kan vi bruke isValidationError her? Skal man kunne trykke på denne knappen i de samme tilfellene som når man det er ett godkjent input? Eller er det tilfeller jeg ikke tenker på?

2020-12-04 08:48 UTC, Trulsaa commented on packages/frontend/src/components/HoursWithdrawal.vue
> +      this.errorMessage = "";
Hvordan fikk du vekk bygg feilen uten å fjerne side effecten her? Jeg tror uansett det er best å ta ut errorMessage fra isValidationError slik at den kun gjør det navnet tilsier.

2020-12-04 08:48 UTC, Trulsaa commented on packages/frontend/src/store/overtime.ts
>  export interface Transaction {
Kan vi gå igjennom det som har blitt gjort med Transaction + venner? Jeg tror transaction blir for generelt som navn.

2020-12-04 08:54 UTC, klyngen commented on packages/frontend/src/components/HoursWithdrawal.vue
> +      this.errorMessage = "";
Byggfeilen sa at det ikke er greit å modifiserer data gjennom en computed-property. Den er ikke lenger computed.

2020-12-08 20:37 UTC, Trulsaa approved these changes
Meget pent!

2020-12-08 20:38 UTC, merged