Feature/sickdays
Alv-no/alvtime pull request #304
Opened 2021-03-30 08:24 UTC by klyngen

This is a PR with a lot of stuff:
- Upgraded to Core 3.1 and standard 2.1
- Easier to develop backend without visual studio. When using docker-compose you can edit backend with hot reaload. Pretty neat.
- SickDays logic for calculating remaining "egenmeldingsdager"

2021-03-30 11:02 UTC, palbock90 requested changes

2021-03-30 11:02 UTC, palbock commented on docker-compose.yaml
> -      - AzureAd__Domain=api://c9126a83-01c3-43c0-8bb3-298d352d2d7f
Disse fjernes fordi de uansett ligger i appsettings.json eller?

2021-03-30 11:02 UTC, palbock commented on packages/api/AlvTime.Business/AbsenseDays/AbsenseDaysService.cs
> +                VacationDaysLeft = vacationDays - vacationEntries.Count(),
Her er det en del edge caser. For det første fører vi i dag ferie på Alv-dagene som betyr at i praksis har vi i snitt litt over 30 feriedager per år, ikke 25. Så det må lages en kalkulator for å legge på antall Alv-dager til de vanlige 25. Det går kanskje an å gjenbruke noe i RedDays.cs I tillegg er det ikke garantert at man fører en full dag ferie hver gang man fører ferie, så det blir vel bedre å regne med timer enn antall entries. I tillegg må det tas hensyn til at man kun har 25 feriedager dersom man startet før 1. januar foregående år. Startet man for eksempel 1. juli har man 13 feriedager tilgjengelig.

2021-03-30 11:02 UTC, palbock commented on packages/api/AlvTime.Business/FlexiHours/IFlexihourRepository.cs
> +        PaidOvertimeEntry RegisterPaidOvertime(GenericHourEntry request, int userId);
Jeg merget en PR til master i dag der denne endringen allerede er gjort, anbefaler å kjøre en merge med master :)

2021-03-30 11:02 UTC, palbock commented on packages/api/AlvTime.Business/FlexiHours/PaidOvertimeEntry.cs
> +        public decimal ValueAfterCompRate { get; set; }
Denne klassen er også endret på i master nå, med HoursBeforeComp og HoursAfterComp. Value er fjernet

2021-03-30 11:02 UTC, palbock commented on packages/api/AlvTimeWebApi/Models/HourEntryRequest.cs
> +        [HalfHour]
HalfHourAttribute.cs sjekker spesifikt på klassenavn, så du må inn der og legge til HourEntryRequest

2021-03-30 11:02 UTC, palbock commented on packages/api/AlvTimeWebApi/Controllers/FlexiHourController.cs
> -            if (response is OkObjectResult)
Her har jeg også gjort et par ting i PR'en som gikk inn i master i dag så vi slipper å kjøre en if for å sjekke responsen. Nå kastes det exceptions med riktig HTTP kode fra inne i logikken i repository klassene

2021-03-30 11:02 UTC, palbock commented on packages/api/AlvTimeWebApi/Controllers/HolidayController.cs
> +            if (!year.HasValue) {
Smart

2021-03-30 11:02 UTC, palbock commented on packages/api/AlvTimeWebApi/Controllers/HolidayController.cs
> +        public ActionResult<AbsenseDaysDto> FetchRemainingAbsenseDays(int ?year, DateTime? intervalStart)
Dette endepunktet returnerer kun gjenværende dager. Kunne det slås sammen med endepunktet over og utvidet AbsenceDaysDto til å inkludere brukte syke- og feriedager også? Kunne kalt den AbsenceOverviewDto for eksempel

2021-03-30 11:02 UTC, palbock commented on packages/api/Tests/UnitTests/Flexihours/CancelPayoutTests.cs
> +            }, 1).Value;
Alle disse testene ble også påvirket av endringene jeg gjorde, så etter merge med master skal de være fine :)

2021-03-30 11:02 UTC, palbock90 commented on docker-compose.yaml
> +      - ASPNETCORE_ENVIRONMENT=development
Lurer på om ikke ASPNETCORE_ENVIRONMENT er case sensitivt på linux, så kanskje greit å bruke 'Development' så er vi helt safe? :D

2021-03-30 11:34 UTC, klyngen commented on docker-compose.yaml
> -      - AzureAd__Domain=api://c9126a83-01c3-43c0-8bb3-298d352d2d7f
Jeg valgte å beholde de for de som ønsker å utvikle uten docker-compose

2021-03-30 11:36 UTC, klyngen commented on packages/api/AlvTime.Business/AbsenseDays/AbsenseDaysService.cs
> +                VacationDaysLeft = vacationDays - vacationEntries.Count(),
Klar over edge casene. Jeg skal prøve å knekke et par av dem.

2021-03-30 11:36 UTC, klyngen commented on packages/api/AlvTime.Business/FlexiHours/IFlexihourRepository.cs
> +        PaidOvertimeEntry RegisterPaidOvertime(GenericHourEntry request, int userId);
Will do

2021-03-30 11:37 UTC, klyngen commented on packages/api/AlvTimeWebApi/Controllers/HolidayController.cs
> +        public ActionResult<AbsenseDaysDto> FetchRemainingAbsenseDays(int ?year, DateTime? intervalStart)
Det er ingen dum ide

2021-03-30 11:38 UTC, klyngen commented on docker-compose.yaml
> +      - ASPNETCORE_ENVIRONMENT=development
Jeg kan sette den til develop med stor D. Det fungerer nå på Linux :)

2021-03-30 11:42 UTC, klyngen commented on packages/api/AlvTime.Business/AbsenseDays/AbsenseDaysService.cs
> +                VacationDaysLeft = vacationDays - vacationEntries.Count(),
Man har jo krav på 25 dager uansett, så jeg kan jo også hente ut ubetalt ferie. Og ut i fra startdato finne ut om det er ferre betalte dager

2021-03-30 12:46 UTC, palbock90 commented on packages/api/AlvTime.Business/AbsenseDays/AbsenseDaysService.cs
> +                VacationDaysLeft = vacationDays - vacationEntries.Count(),
Ja, vi kan godt ha separate bokser for betalt og ubetalt ferie

2021-04-05 21:28 UTC, klyngen commented
![image](https://user-images.githubusercontent.com/14232560/113629367-a55b8080-9666-11eb-8eae-103e6e9aa6e0.png)

2021-04-05 22:05 UTC, Trulsaa requested changes

2021-04-05 22:05 UTC, Trulsaa commented on docker-compose.yaml
> +      - REACT_APP_CLIENT_ID=c9126a83-01c3-43c0-8bb3-298d352d2d7f
Disse innstillingene har blitt flyttet inn i public/config.json

2021-04-05 22:05 UTC, Trulsaa commented on docker-compose.yaml
> +      - VUE_APP_CLIENT_ID=c9126a83-01c3-43c0-8bb3-298d352d2d7f
Disse innstillingene har blitt flyttet inn i public/config.json

2021-04-05 22:06 UTC, Trulsaa commented
Jeg startet på en review her men ser det er ganske mye som ikke er med fra master. Kan du rebase på toppen av master så kan jeg gjerne se litt videre :)

2021-04-06 06:26 UTC, palbock90 commented
> 
> 
> ![image](https://user-images.githubusercontent.com/14232560/113629367-a55b8080-9666-11eb-8eae-103e6e9aa6e0.png)

Har ikke sett på koden enda, men et par tanker til bildet:
1.  Jeg syns fraværsdager bure være på sin egen side. Da er det enkelt for oss å utvide med mer ting senere, som noe kalenderfunksjonalitet, statistikker osv. I tillegg føler jeg det blir for mye info på en side, spesielt når fraværsdagene egentlig ikke har noe med timebanken å gjøre.
2. Beskrivelsen til baren er litt vag. Burde kanskje spesifiseres at dette er fraværsdager _tilgjengelig/brukt_ så langt i år. Når det bare står Alvdager der skjønner jeg ikke umiddelbart om det er Alvdager jeg har ført ferie på, om det er Alvdager som har vært i år eller totalt antall Alvdager i 2021.
3. Skulle gjerne sett både dager brukt og dager tilgjengelig. Om det blir to separate barer, eller om det finnes en annen måte å visualisere det på vet jeg ikke.

Tanker? Det er lov å være uenig :) @martiskj @klyngen @Trulsaa

2021-04-06 08:12 UTC, klyngen commented
> > ![image](https://user-images.githubusercontent.com/14232560/113629367-a55b8080-9666-11eb-8eae-103e6e9aa6e0.png)
> 
> Har ikke sett på koden enda, men et par tanker til bildet:
> 
>     1. Jeg syns fraværsdager bure være på sin egen side. Da er det enkelt for oss å utvide med mer ting senere, som noe kalenderfunksjonalitet, statistikker osv. I tillegg føler jeg det blir for mye info på en side, spesielt når fraværsdagene egentlig ikke har noe med timebanken å gjøre.
> 
>     2. Beskrivelsen til baren er litt vag. Burde kanskje spesifiseres at dette er fraværsdager _tilgjengelig/brukt_ så langt i år. Når det bare står Alvdager der skjønner jeg ikke umiddelbart om det er Alvdager jeg har ført ferie på, om det er Alvdager som har vært i år eller totalt antall Alvdager i 2021.
> 
>     3. Skulle gjerne sett både dager brukt og dager tilgjengelig. Om det blir to separate barer, eller om det finnes en annen måte å visualisere det på vet jeg ikke.
> 
> 
> Tanker? Det er lov å være uenig :) @martiskj @klyngen @Trulsaa

Enig i at dette eventuelt kan flyttes til feriemenyen. Tenker vi kunne endret litt på teksten slik at man i stedet for å vise 6, 22 og 6 viser 6/7 22/25 og 6/12. Blir det ikke da enklere å forstå at hva man har hatt. Det man ikke ser i det bildet, er at baren krymper når man bruker dager. Jeg ser ikke nødvendigvis behovet for å se hvor mange dager jeg har brukt, men vil jo alltid ønske å vise hvor mange jeg har igjen.

Det som gjerne kan diskuteres, er hvordan man viser planlagt / brukt ferie. Om du nå fører ferie i juli, så vil de trekkes fra i baren. Men det er planlagt ferie og ikke brukt.

![image](https://user-images.githubusercontent.com/14232560/113679559-2eeb6c80-96c0-11eb-82d9-acbd713ef35e.png)

2021-04-06 16:56 UTC, palbock90 commented
> Enig i at dette eventuelt kan flyttes til feriemenyen. Tenker vi kunne endret litt på teksten slik at man i stedet for å vise 6, 22 og 6 viser 6/7 22/25 og 6/12. Blir det ikke da enklere å forstå at hva man har hatt. Det man ikke ser i det bildet, er at baren krymper når man bruker dager. Jeg ser ikke nødvendigvis behovet for å se hvor mange dager jeg har brukt, men vil jo alltid ønske å vise hvor mange jeg har igjen.
> 
> Det som gjerne kan diskuteres, er hvordan man viser planlagt / brukt ferie. Om du nå fører ferie i juli, så vil de trekkes fra i baren. Men det er planlagt ferie og ikke brukt.
> 
> ![image](https://user-images.githubusercontent.com/14232560/113679559-2eeb6c80-96c0-11eb-82d9-acbd713ef35e.png)
> 
> Foreslåtte endringer visualisert. (pluss at man flytter baren til ferie)
> ![image](https://user-images.githubusercontent.com/14232560/113680198-e08a9d80-96c0-11eb-91d3-d8184d26b81e.png)

Jeg synes kanskje fortsatt at det litt uklart og at det hadde blitt tydeligere ved å legge til "feriedager tilgjengelig" eller noe sånt over baren. @martiskj hadde også et poeng med at kanskje ikke vi skulle hatt egenmeldingsdagene i samme baren, da det ikke er noe man "bruker" på samme måte som ferie.

Forsåvidt enig i at det i seg selv ikke er så interessant å se hvor mange dager man har brukt, men det som kan være interessant er jo en kalenderoversikt med _når_ man har brukt ferien sin til nå. Det kan jo legges til på et senere tidspunkt.

2021-05-08 08:45 UTC, palbock90 commented on packages/api/AlvTime.Business/AbsenseDays/AbsenseDaysService.cs
>              IEnumerable<TimeEntriesResponseDto> sickLeaveDays = timeEntryStorage.GetTimeEntries(new TimeEntryQuerySearch
Kunne det vært en idè å snu litt på flyten her? Nå går det Controller -> Business layer -> Repository layer. Det gjør at business logikken må vite noe om data access og hvor den får dataen sin fra. Alternativt kunne vi gått Controller -> Repository -> Business, slik at business ikke trenger å bry seg om hvordan den får dataen sin, den bare gjør noen utregninger og sender det tilbake igjen.

2021-05-08 08:46 UTC, palbock90 commented
Koden ser grei ut ved første øyekast, men får ikke sjekka ut branchen for å teste det in action. Får den feilen her: 
![image](https://user-images.githubusercontent.com/41721443/117533015-a62b5d80-afea-11eb-8acf-c836090035a9.png)
Noen anelse om hva det kommer av?

2021-05-09 21:01 UTC, klyngen commented on packages/api/AlvTime.Business/AbsenseDays/AbsenseDaysService.cs
>              IEnumerable<TimeEntriesResponseDto> sickLeaveDays = timeEntryStorage.GetTimeEntries(new TimeEntryQuerySearch
Nei. I en lagdelt modell så skal man egentlig ha Presentation -> Business -> Persistance-Layer. Det er jo faktisk slik at business ikke har noe forhold til noe annet enn et interface. Arkitektur-messig, er koden mere riktig enn mye av den andre koden som finnes i Alvtime

2021-05-10 06:30 UTC, palbock90 commented on packages/api/AlvTime.Business/AbsenseDays/AbsenseDaysService.cs
>              IEnumerable<TimeEntriesResponseDto> sickLeaveDays = timeEntryStorage.GetTimeEntries(new TimeEntryQuerySearch
Vi burde egentlig ta en arkitektur-oppvask i Alvtime tror jeg. Helt enig i at lagdelt arkitektur er sånn du sier, men jeg tror resten av Alvtime er løst basert på onion architecture, men det har blitt en slags Frankensteins monster arkitekturmessig :P Tar gjerne en diskusjon på hvordan vi har mest lyst til å strukturere prosjektene våre så vi kan få ryddet opp!

2021-05-10 07:58 UTC, klyngen commented on packages/api/AlvTime.Business/AbsenseDays/AbsenseDaysService.cs
>              IEnumerable<TimeEntriesResponseDto> sickLeaveDays = timeEntryStorage.GetTimeEntries(new TimeEntryQuerySearch
Akkurat nå er det litt vanskelig å se at vi prøver å lage en lauk-arkitektur :laughing: men enig i at vi burde ta en runde på det. Nå har jo jeg gått for en lag-delt approach, og årsaken til det er at det så litt ut som om vi hadde en halvhjertet lag-delt model.

2021-05-22 15:16 UTC, Trulsaa commented
Changes merged in #339

2021-05-22 15:16 UTC, closed without merging