Use CORS to open up for frontend and adminpanel
Alv-no/alvtime pull request #308
Opened 2021-03-31 18:54 UTC by Trulsaa

2021-03-31 20:03 UTC, palbock90 requested changes

2021-03-31 20:03 UTC, palbock commented on packages/charts/service/data/api/test-env.yaml
> +  ASPNETCORE_ENVIRONMENT: "Production"
Tror ikke det er helt optimalt å sette denne til 'Production' i test-env. Det vil blant annet gjøre at vi får mindre detaljerte feilmeldinger i test.

2021-03-31 20:03 UTC, palbock90 commented on packages/api/AlvTimeWebApi/Startup.cs
> +                        var origins = Configuration["AllowedOrigins"].Split(",");
Trekk gjerne denne variabelen utenfor services.AddCors(){}. Hvis du føler deg ekstra eventyrlysten kan du trekke hele CORS konfigureringen ut i en ekstern klasse tilsvarende som er gjort med Autoriseringskonfigen. Hvis du ser på AuthorizationExtension.cs så har den en metode som heter AddAlvtimeAuthorization som brukes i Startup.cs.

2021-04-01 12:34 UTC, Trulsaa commented on packages/charts/service/data/api/test-env.yaml
> +  ASPNETCORE_ENVIRONMENT: "Production"
Den er nå satt til Staging slik at CORS kun disables i lokalt utviklings miljø og stack trace logging kun disables i produksjon.

2021-04-01 12:34 UTC, Trulsaa commented on packages/api/AlvTimeWebApi/Startup.cs
> +                        var origins = Configuration["AllowedOrigins"].Split(",");
Kall meg gjerne Askeladden.

2021-04-03 14:51 UTC, palbock90 approved these changes
Ser bra ut nå 👍

2021-04-03 19:13 UTC, merged