Write shell scripts for plan, build and deploy of infrastructure and services
Alv-no/alvtime pull request #310
Opened 2021-04-05 12:58 UTC by Trulsaa

2021-04-06 14:11 UTC, Trulsaa commented
Tips til reviewer. start med å se på det som har blitt lagt til i run fila. Der kan man se hvordan scriptene er tenkt å bli kjørt.

2021-04-06 17:04 UTC, palbock90 submitted a review, later dismissed
Har ikke så mye å komme med her. Ser greit ut, men vanskelig å si uten å teste den faktiske pipelinen :) Approver så du kan merge, men har ikke noe særlig input til endringene

2021-04-08 16:17 UTC, lundatic requested changes
Sett igjennom. Ønsker at man godtar case-insensitiv innskrivning av dev og prod når man kjører run-scriptet

2021-04-08 16:21 UTC, lundatic approved these changes
Nå ser det konge ut!

2021-04-08 16:22 UTC, merged