Add architecture drawing
Alv-no/alvtime pull request #348
Opened 2021-06-06 12:50 UTC by Trulsaa

2021-06-06 15:01 UTC, palbock90 commented
Jeg får fnatt av at det ikke er rette linjer mellom boksene, men det er kanskje bare meg :P 
Syns tegningen ser bra ut, kunne eventuelt utvidet med litt tekst om hva som skjer mellom boksene. For eksempel hvilken auth flow som brukes med no JWT som sendes frem og tilbake osv.

2021-06-06 15:36 UTC, Trulsaa commented
Når jeg prøvde med rette linjer så så det bare ut som alt var koblet til alt. Sikkert mulig å tegne det bedre. Målet her er egentlig bare å gi akkurat nok info til å kunne forstå hva som må kjøres opp for å kunne utvikle. Jeg tror da Auth greier blir litt mye info (Jeg fikk det ikke inn i diagrammet uten at det så rotete ut).

2021-06-10 19:38 UTC, idatheo submitted a review, later dismissed

2021-06-10 19:38 UTC, idatheo commented on Readme.md
> +- [.NET Core 14](https://dotnet.microsoft.com/download/dotnet/3.1)
Er det nødvendig å spesifisere hvilken versjon? (Krever regelmessig oppdatering av dokumentasjon)

2021-06-10 19:38 UTC, idatheo commented on Readme.md
> +A docker compose development environment has been defined for this project in `docker-compose.yaml`. This enables the whole or part of the local environment to be started using docker. Several helper
Note to n00b: skal kjøres på rot, ikke under packages/frontend

2021-06-10 19:38 UTC, idatheo commented on Readme.md
>  Run `./run build` from the root of the project.
her har du presisert hvor man skal kjøre kommandoene fra. Bra!

2021-06-10 19:38 UTC, idatheo commented on packages/adminpanel/.devcontainer.json
> -    "octref.vetur",
dette er jo ikke en readme-endring. Hva endres her?

2021-06-10 19:38 UTC, idatheo commented on packages/frontend/src/components/HoursWithdrawal.vue
> +          <OvertimeVisualizer :bar-data="holidayData"></OvertimeVisualizer>
dette er noe mer enn bare dokumentasjonsforbedring. Hva er dette?

2021-06-10 20:42 UTC, Trulsaa commented on packages/frontend/src/components/HoursWithdrawal.vue
> +          <OvertimeVisualizer :bar-data="holidayData"></OvertimeVisualizer>
Detter er noe vue sin linter har gjort når jeg kjørte den. Resultatet har fått sin egen kommit. Forbedringen av dette er at vi kjører linting og dermed automatsik formattering på en commit hook.

2021-06-10 20:43 UTC, Trulsaa commented on packages/adminpanel/.devcontainer.json
> -    "octref.vetur",
Her fjerner jeg en vue plugin fra en devcontainer der man kun skal utvikle react. Dette har fått sin egen commit :)

2021-06-10 20:43 UTC, Trulsaa commented on Readme.md
> +A docker compose development environment has been defined for this project in `docker-compose.yaml`. This enables the whole or part of the local environment to be started using docker. Several helper
Godt poeng. I fix!

2021-06-10 20:47 UTC, Trulsaa commented on Readme.md
> +- [.NET Core 14](https://dotnet.microsoft.com/download/dotnet/3.1)
Hvordan skal man da vite hvilken versjon man skal innstallere? Jeg vet at det står i Dockerfile også. Men kan jeg forvente at de som skal onboarde vet det?

2021-06-10 20:51 UTC, Trulsaa commented
Jeg vet det er masse skrivefeil her.  Kunne flere tatt en titt og gitt tilbakemelding på om det gir mening det jeg har skevet. Hva mangler for at man skal forstå hvordan kjøre opp og bidra?

2021-06-11 08:44 UTC, palbock90 requested changes

2021-06-11 08:44 UTC, palbock90 commented on Readme.md
> +Whenever a dependency is added to the frontend or the backend code is changed you have to rebuild the container to see the changes. This is done by shutting down the environment `./run down` and runn
Skrivefeil: "for eksample" -> "for example"

2021-06-11 08:44 UTC, palbock90 commented on Readme.md
> +A docker compose development environment has been defined for this project in `docker-compose.yaml`. This enables the whole or part of the local environment to be started using docker. Several helper
Kanskje spesifisere at ./run frontend også starter API og database?

2021-06-11 08:44 UTC, palbock90 commented on packages/frontend/README.md
> +From this folder run `npm install` and `npm start`, then open the frontend in your browser at `localhost:8080`. This starts a development server that recompiles when the code is changed. For the fron
Kan du si noe om hvor man eventuelt endrer hvilken URL backend finnes på siden det kan være forskjellig avhengig av hvordan man starter backend?

2021-06-11 17:41 UTC, Trulsaa commented
Fikset😊 @palbock90

2021-06-14 05:56 UTC, timorzadir commented on Readme.md
> +- [.NET Core 14](https://dotnet.microsoft.com/download/dotnet/3.1)
Det skal vel stå .NET Core 3.1, ikke 14.

2021-06-15 12:49 UTC, palbock90 approved these changes
Nå ser det bra ut!

2021-06-15 13:28 UTC, merged