Button-less-login
Alv-no/alvtime pull request #389
Opened 2021-09-02 23:36 UTC by klyngen

Pressing login button is no longer required
Also transitioning over to axios with a neat httpClient that has a
middleware resolving the bearer-token

2021-09-03 12:16 UTC, palbock90 commented
Ser ikke navnet til innlogget bruker i hamburgermenyen:
![image](https://user-images.githubusercontent.com/41721443/132003781-171b37fb-c2a6-4a9d-a0be-c90442f6135c.png)

2021-09-03 13:01 UTC, klyngen commented
> Ser ikke navnet til innlogget bruker i hamburgermenyen:
> ![image](https://user-images.githubusercontent.com/41721443/132003781-171b37fb-c2a6-4a9d-a0be-c90442f6135c.png)

Det er fordi du er logget inn som Ahre Ketil. Om du er logget inn med din faktiske bruker, så vil navnet vises :)

2021-09-03 17:49 UTC, Trulsaa commented on packages/frontend/src/services/auth.ts
> +const scopes = [config.ACCESS_SCOPE];
Kunne vi ha lagt denne inne i klassen? Den ser så malplasert ut.

2021-09-03 17:52 UTC, Trulsaa commented on packages/frontend/src/services/auth.ts
> +  }
Denne hadde veldig rar logikk :P

2021-09-03 17:58 UTC, Trulsaa commented on packages/frontend/src/services/auth.ts
> +  private accountLoaded$: Promise<AccountInfo>;
Jeg syntes AccountInfor bør være lagret i kun 1 variabel. Altså omgjøre acountsLoaded til Promise<boolean> og alltid lagre AccountInfo i accountInfo. Eller noe lignende det. accountLoaded blir i allefall et misvisende navn om den ikke returnerer en boolean.

2021-09-03 18:37 UTC, Trulsaa commented on packages/frontend/src/store/tasks.ts
> -        commit("SET_USER_NOT_FOUND");
Blir digg å få flyttet denne inn i en middleware :) Ser den har blitt kopiert rundt i hele koden nå 😂

2021-09-03 18:44 UTC, Trulsaa commented on packages/frontend/src/store/timeEntries.ts
> +            if (e.status !== 200) {
Denne if statementen kan vel aldri bli true.

2021-09-03 18:45 UTC, Trulsaa commented on packages/frontend/src/store/timeEntries.ts
> +            }
Jeg vil tro dette er noe som henger igjen fra gamle dager da APIet ikke var helt 👍 Kanskje gjøre en liten test og sjekke om det fortsatt trengs?

2021-09-03 18:48 UTC, Trulsaa commented on packages/frontend/src/store/timeEntries.ts
>        try {
Trenger vi fortsatt denne try catch blocka med all disse flotterse then().catch() lenkene 😎

2021-09-03 18:49 UTC, Trulsaa commented on packages/frontend/src/store/timeEntries.ts
> +        if (!Array.isArray(response.data) && response.data.message) {
Trenger vi virkelig denne lenger? Jeg har lyst til å tro att dette er noe som henger igjen fra gamle dager.

2021-09-03 18:56 UTC, Trulsaa commented
<img width="874" alt="Screenshot 2021-09-03 at 20 54 01" src="https://user-images.githubusercontent.com/15033235/132053678-50161180-ee78-41a9-a9c5-87fbdce91fa9.png">
Jeg kommer ikke inn i appen og får ☝️ i consolen når jeg prøver å teste dette etter å ha satt isDevMode til false.

2021-09-05 15:37 UTC, FredrikAugust commented on packages/frontend/src/store/timeEntries.ts
> +          .post<any[]>(
Kan denne types til en type? 

Hvis det er vanskelig går det også an å type det til input-et til `createTimeEntrie`;

```ts
Array<Parameters<typeof createTimeEntrie>[0]>
```

Men det er kanskje ikke det klareste eller mest leselige i verden

2021-09-05 15:40 UTC, FredrikAugust commented on packages/frontend/src/store/tasks.ts
>    PUSH_TASKS: async (
Denne trenger ikke `async`-keywordet hvis den ikke skal bruke `async/await`, det holder at den bruker `Promise.then`. Evt. kan den skrives om til å bruke `try/catch` rundt `async/await`-kall.

```suggestion
  PUSH_TASKS: (
```

2021-09-05 15:43 UTC, FredrikAugust commented on packages/frontend/src/store/timeEntries.ts
> +          .post<any[]>(
Jeg ser nå at parameterene til `createTimeEntrie` er `any` også. Kanskje vi kan type det vi vet vi trenger ved å endre på `createTimeEntrie`? 

```ts
function createTimeEntrie<T extends { date: string, value: number }>(data: T): FrontendTimentrie {
```

og 

```suggestion
          .post<Array<Parameters<typeof createTimeEntrie>[0]>>(
```

Det vil i hvert fall være en start på å få solid typing

2021-09-05 15:45 UTC, FredrikAugust commented on packages/frontend/src/store/overtime.ts
> +    await httpClient
Trengs denne å awaites (og funksjonen å være `async`) når vi bruker `Promise.then`?

2021-09-05 21:06 UTC, Trulsaa commented on packages/frontend/src/components/GenerateToken.vue
>      async fetchAccessToken() {
async trengs vel ikke lenger

2021-09-05 21:07 UTC, Trulsaa commented on packages/frontend/src/components/FavoriteSelector.vue
> +    await this.$store.dispatch("FETCH_TASKS");
async / await trengs vel ikke her

2021-09-05 21:18 UTC, Trulsaa commented on packages/frontend/src/components/TimeEntrieDayList.vue
> +  async created() {
her trengs vel ikke async

2021-09-05 21:18 UTC, Trulsaa commented on packages/frontend/src/components/TimeEntrieWeekList.vue
> +  async created() {
her trengs vel ikke async

2021-09-05 21:57 UTC, Trulsaa commented on packages/frontend/src/components/ErrorSnackbar.vue
> +    },
Disse ser ikke ut til å brukes noe sted

2021-09-05 22:03 UTC, Trulsaa commented on packages/frontend/src/components/TimeEntrieDayList.vue
> +  },
Kan denne flyttes opp i Hours.vue?

2021-09-05 22:03 UTC, Trulsaa commented on packages/frontend/src/components/TimeEntrieWeekList.vue
> +  },
Kan denne flyttes opp i Hours.vue?

2021-09-05 22:59 UTC, Trulsaa commented on packages/frontend/src/services/httpClient.ts
> +    // means that we used a token and the token was not accepted
På linje 42 settes det på et token på de urlene som er protected og ellers ikke. Altså blir vel denne kommentaren feil?

2021-09-05 23:21 UTC, Trulsaa requested changes, later dismissed
Her ble det mange endringer som må testes grundig før det merges. Jeg skulle helst sett at dette ble splittet opp i to PRer. En for Login og en for Error håndtering. På den måten kan man få gjennomført kodereview og testing mye raskere.

2021-09-16 16:47 UTC, FredrikAugust reviewed
lgtm

2021-09-16 16:47 UTC, FredrikAugust approved these changes

2021-09-16 16:48 UTC, merged