626 interval selections
Alv-no/alvtime pull request #643
Opened 2023-03-02 20:14 UTC by martehvi

2023-03-02 21:04 UTC, klyngen requested changes
A few comments to lift the quality 🏋️

2023-03-02 21:04 UTC, klyngen commented on packages/frontend/src/components/SimpleDatePicker.vue
> +      console.log("the gold");
Remove console logs

2023-03-02 21:04 UTC, klyngen commented on packages/frontend/src/components/InvoiceStatistics.vue
> +.statistic-cards>div {
Nit: add spacing

2023-03-02 21:04 UTC, klyngen commented on packages/frontend/src/components/IntervalShortcuts.vue
> +    defaultDate: {
Don't think this prop is used anywhere

2023-03-02 21:04 UTC, klyngen commented on packages/frontend/src/components/IntervalShortcuts.vue
> +      var month = today.getMonth() + 1;
There is a lot of repetitive code in this function and I know we can do better.

How I would think about a component like this:
- property label: string
- property months: number

Emits a toDate and a fromDate

No need to have a switch that switches on strings 😄

And the variables in data can be removed when those changes are done. 

I can explain in more detail if you have questions.

2023-03-02 21:04 UTC, klyngen commented on packages/frontend/src/components/InvoiceStatisticCard.vue
> +        <div class="value"><b>{{ value.value }}</b></div>
Semantics save lives 🎉

2023-03-02 21:08 UTC, klyngen requested changes

2023-03-02 21:08 UTC, klyngen commented on packages/frontend/src/components/IntervalShortcuts.vue
> +          this.toDate = moment(today).format("YYYY-MM-DD");
Don't think the usage of moment is needed. There are some methods in the invoice-store. Extract those methods into a util file and use the same component here. All dependencies in Javascript are technical debt 🤓

2023-08-30 10:19 UTC, Fordiboii commented
Closing, implemented in https://github.com/Alv-no/alvtime/pull/690

2023-08-30 10:19 UTC, closed without merging