Feature/refactor customers page
Alv-no/alvtime pull request #897
Opened 2024-10-10 05:59 UTC by rsletta

https://github.com/user-attachments/assets/ec50dae5-fc75-4e6e-b324-7313d31399ba

- adds customer cards
- filtering on customers

2024-10-10 06:30 UTC, palbock requested changes

2024-10-10 06:30 UTC, palbock commented on packages/adminpanel/Client/Pages/Customers/Customers.razor
> +    private void FilterCustomers()
Kan den gamle FilterCustomer-metoden fjernes?

2024-10-10 06:30 UTC, palbock commented on packages/adminpanel/Client/Pages/Customers/Customers.razor
> +    private void NavigateToCustomer(int customerId)
Brukes denne metoden lenger?

2024-10-10 06:30 UTC, palbock commented on packages/adminpanel/Client/Shared/components/CustomerCard.razor
> +    [Parameter] public string? AvatarImageUrl { get; set; }
Regner med at flere av disse parameterene er tenkt til å tas i bruk senere?

2024-10-10 06:37 UTC, rsletta commented on packages/adminpanel/Client/Pages/Customers/Customers.razor
> +    private void NavigateToCustomer(int customerId)
planen er å bruke den straks.

2024-10-10 06:37 UTC, rsletta commented on packages/adminpanel/Client/Shared/components/CustomerCard.razor
> +    [Parameter] public string? AvatarImageUrl { get; set; }
korrekt

2024-10-10 06:38 UTC, rsletta commented on packages/adminpanel/Client/Pages/Customers/Customers.razor
> +    private void FilterCustomers()
godt fanget opp. den skal bort. fikser.

2024-10-10 12:00 UTC, palbock commented on packages/api/AlvTimeWebApi/Responses/Admin/CustomerDetailedResponse.cs
Burde denne renames til CustomerAdminResponse?

2024-10-10 21:39 UTC, rsletta commented on packages/api/AlvTimeWebApi/Responses/Admin/CustomerDetailedResponse.cs
Absolutt et bedre navn.

2024-10-11 08:41 UTC, palbock approved these changes

2024-10-11 09:12 UTC, merged